rx-java/src/main/java/io/vertx/rx/java/UnmarshallerOperator.java
Currently each onCompleted call creates new instance of ObjectMapper, which degrades performance.
=> Don't create new ObjectMapper on every onCompleted

rx-groovy/src/main/java/io/vertx/rx/groovy/RxHelper.java, rx-java/src/main/asciidoc/dataobjects.adoc, rx-java/src/main/java/io/vertx/rx/java/ContextScheduler.java, rx-java/src/main/java/io/vertx/rx/java/RxHelper.java, rx-java/src/main/java/io/vertx/rxjava/core/RxHelper.java, rx-java/src/test/java/META-INF/MANIFEST.MF, rx-java/src/test/java/io/vertx/rx/java/test/SchedulerTest.java
Community patch by @kevlarC + improvements.
@kevlarC would you mind to review the pull request please ?
=> Context scheduler

rx-java/pom.xml
Added bnd configuration to all auth providers to generate OSGi manifests. Test cases are available in a Bndtools workspace here: https://github.com/paulbakker/vertx-osgi-testcases/tree/master
Note that this requires the unreleased bnd-maven-plugin 3.2 plugin.
=> Bnd configuration for generating OSGi metadata

rx-java/src/main/java/examples/NativeExamples.java, rx-java/src/main/java/examples/RxifiedExamples.java
Replacing deprecated rx.plugins.RxJavaPlugins.getInstance() in examples with  rx.plugins.RxJavaHooks.
=> Replacing deprecated rx.plugins.RxJavaPlugins.getInstance()  

rx-java/src/main/asciidoc/dataobjects.adoc, rx-java/src/main/java/io/vertx/lang/rxjava/TypeArg.java, rx-java/src/main/resources/vertx-rxjava/template/class.templ, rx-java/src/main/resources/vertx-rxjava/template/classbody.templ, rx-java/src/main/resources/vertx-rxjava/template/common.templ, rx-java/src/test/java/io/vertx/rx/java/test/JavaIntegrationTest.java, rx-java/src/test/java/io/vertx/rx/java/test/api/GenericsTCKTest.java
Provides support for `GenericApi<String>` as argument and return types and support for `<U> GenericApi<U> m(Class<U>)` or even `U m(Class<U>)`
=> Generics improvements

rx-java/src/main/asciidoc/java/index.adoc, rx-java/src/main/java/examples/RxifiedExamples.java, rx-java/src/main/java/io/vertx/rx/java/CompletableOnSubscribeAdapter.java, rx-java/src/main/java/io/vertx/rxjava/core/package-info.java, rx-java/src/main/resources/vertx-rxjava/template/class.templ, rx-java/src/main/resources/vertx-rxjava/template/common.templ, rx-java/src/test/java/io/vertx/rx/java/test/CoreRxifiedApiTest.java
Motivation:
the new _rxABC_ methods generate `Single<Void>`, RxJava provides the `Completable` type that is the right rx type that should be used.
Changes:
now the generator creates `Completable` types instead of `Single<Void>` with the corresponding adapter.
=> Use Completable instead of Single<Void> - fixes #77

rx-java/src/main/resources/vertx-rxjava/template/class.templ, rx-java/src/main/resources/vertx-rxjava/template/common.templ, rx-java/src/test/java/io/vertx/codegen/extra/ConcreteInheritsToString.java, rx-java/src/test/java/io/vertx/codegen/extra/ConcreteOverridesToString.java, rx-java/src/test/java/io/vertx/codegen/extra/NonConcreteWithToString.java, rx-java/src/test/java/io/vertx/rx/java/test/EqualityTest.java, rx-java/src/test/java/io/vertx/rx/java/test/ToStringTest.java, rx-java2/src/test/java/io/vertx/reactivex/test/EqualityTest.java, rx-java2/src/test/java/io/vertx/reactivex/test/ToStringTest.java
Fixes #106
All generated classes now call equals/hashCode on the delegate.
=> Invoke equals, hashCode and toString on delegate

rx-java2/src/main/java/io/vertx/reactivex/core/impl/ObservableReadStream.java, rx-java2/src/test/java/io/vertx/reactivex/test/FlowableReadStreamAdapterBackPressureTest.java, rx-java2/src/test/java/io/vertx/reactivex/test/ObservableReadStreamAdapterTest.java
=> RxJava2 ObservableReadStream: set handlers before signaling subscription to the observer

rx-java2-codegen/src/main/java/io/vertx/reactivex/FlowableHelper.java, rx-java2-codegen/src/main/java/io/vertx/reactivex/ObservableHelper.java, rx-java2-codegen/src/test/java/io/vertx/reactivex/test/HelperTest.java, rx-java2/src/main/java/io/vertx/reactivex/core/RxHelper.java
I noticed work I've done on RxJava tracing didn't work here due to
skipped assembly hooks. Whenever custom Observable type is instantiated,
it should go through `RxJavaPlugins.onAssembly()`
See https://github.com/square/retrofit/pull/2721
Note: this doesn't do this for rx types new'ed via codegen, as I don't
know how. While this change fixes my immediate issue, likely we'll want
to adjust something to ensure codegen either doesn't new up rx types
directly (ex more use of helpers, even for single and maybe), or that
the codegen does the `onAssembly` hook.
=> Makes sure assembly hooks are called when bridging a vertx type to an rxjava2 type

rx-gen/pom.xml, rx-gen/src/main/asciidoc/vertx-rx/java/index.adoc, rx-gen/src/main/assembly/artifact.xml, rx-java/pom.xml, rx-java2/pom.xml
See comment [link](https://github.com/vert-x3/vertx-rx/issues/172#issuecomment-445031819) for details
- made a OSGI bundle from rx-gen module
- added explicit imports for Import-Package in rx-java/rx-java2 modules
- changed rx-java-gen and rx-java2-gen dependencies scope (do we really need them in runtime?)
=> rx-gen module can't be used in OSGI environment - fixes #172

rx-gen/src/test/java/io/vertx/lang/rx/test/FakeWriteStream.java, rx-java-gen/src/main/java/io/vertx/rx/java/WriteStreamSubscriber.java, rx-java-gen/src/main/java/io/vertx/rx/java/impl/WriteStreamSubscriberImpl.java, rx-java-gen/src/test/java/io/vertx/rx/java/test/WriteStreamSubscriberTest.java, rx-java/src/main/asciidoc/vertx-rx/java/index.adoc, rx-java/src/main/java/examples/RxifiedExamples.java, rx-java/src/test/java/io/vertx/it/AsyncFileTest.java, rx-java2-gen/src/main/java/io/vertx/reactivex/WriteStreamObserver.java, rx-java2-gen/src/main/java/io/vertx/reactivex/WriteStreamSubscriber.java, rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamObserverImpl.java, rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamSubscriberImpl.java, rx-java2-gen/src/test/java/io/vertx/reactivex/test/WriteStreamObserverTest.java, rx-java2-gen/src/test/java/io/vertx/reactivex/test/WriteStreamSubscriberTest.java, rx-java2/src/main/asciidoc/vertx-rx/java2/index.adoc, rx-java2/src/main/java/examples/RxifiedExamples.java, rx-java2/src/test/java/io/vertx/it/AsyncFileTest.java
Closes #218 
The current onComplete callback is tricky because the underlying WriteStream might outstanding writes after the end() method returns.
In this PR, new callbacks are added to handle end(Handler) events.
The onComplete callbacks is deprecated for 3.8.6 and will be removed in 4.0.
=> WriteStream adapter callbacks

pom.xml, rx-junit5-providers/pom.xml, rx-junit5-providers/vertx-junit5-rx-java/pom.xml, rx-junit5-providers/vertx-junit5-rx-java/src/main/java/io/vertx/junit5/rxjava/VertxParameterProvider.java, rx-junit5-providers/vertx-junit5-rx-java/src/main/resources/META-INF/services/io.vertx.junit5.VertxExtensionParameterProvider, rx-junit5-providers/vertx-junit5-rx-java/src/test/java/io/vertx/junit5/rxjava/RxJava1Test.java, rx-junit5-providers/vertx-junit5-rx-java2/pom.xml, rx-junit5-providers/vertx-junit5-rx-java2/src/main/java/io/vertx/junit5/rxjava2/VertxParameterProvider.java, rx-junit5-providers/vertx-junit5-rx-java2/src/main/resources/META-INF/services/io.vertx.junit5.VertxExtensionParameterProvider, rx-junit5-providers/vertx-junit5-rx-java2/src/test/java/io/vertx/junit5/rxjava2/RxJava2Test.java
This transplants the code from `vertx-junit5-extensions` with the RxJava 1 + 2 bindings for `Vertx` objects to be injected in tests.
Note that the branch is based on a branch that does not passes tests for `vertx-rx-java`, see #221
=> JUnit5 providers

rx-java2-gen/src/test/java/io/vertx/codegen/extra/DuplicatesInterface.java, rx-java2-gen/src/test/java/io/vertx/codegen/extra/DuplicatesInterfaceImpl.java, rx-java2-gen/src/test/java/io/vertx/codegen/extra/duplicates/SomeRandomType.java, rx-java2-gen/src/test/java/io/vertx/codegen/extra/duplicates/nested/SomeRandomType.java
Bug reproducer where having 2 types with the same name causes an ambiguous import
=> Bug reproducer where having 2 types with the same name causes an ambiguous import

rx-gen/src/main/java/io/vertx/lang/rx/AbstractRxGenerator.java, rx-java-gen/src/main/java/io/vertx/lang/rxjava/RxJavaGenerator.java, rx-java2-gen/pom.xml, rx-java2-gen/src/main/java/io/vertx/lang/reactivex/RxJava2Generator.java, rx-java2-gen/src/main/java/io/vertx/reactivex/SingleHelper.java, rx-java2-gen/src/test/java/io/vertx/codegen/rxjava2/MethodWithFunction.java, rx-java2-gen/src/test/java/io/vertx/codegen/rxjava2/MethodWithFuture.java, rx-java2-gen/src/test/java/io/vertx/reactivex/test/HelperTest.java, rx-java2-gen/src/test/java/io/vertx/reactivex/test/OverloadMethodsTest.java, rx-java2-gen/src/test/stubs/io/vertx/core/Future.java, rx-java2-gen/src/test/stubs/io/vertx/core/streams/Pipe.java, rx-java2-gen/src/test/stubs/io/vertx/core/streams/ReadStream.java, rx-java2-gen/src/test/stubs/io/vertx/core/streams/WriteStream.java, rx-java2/src/test/java/io/vertx/it/WebClientTest.java, rx-java2/src/test/java/io/vertx/reactivex/jdbcclient/JDBCTest.java
Integration Single and Function type with generation, e.g Single param is aliased into Future and `java.util.function.Function` will rewrite arguments and be thus aliased to `io.reactivex.functions.Function`:
```
void doSomething(Single s);
void doSomething(Future s);
```
```
void doSomething(Function<String, Single<String>> s);
void doSomething(io.reactivex.functions.Function<String, Future<String>> s);
```
This was already existing for `ReadStream` rewritten to `Flowable`
This allows `SqlClient#withTransaction(Function<SqlClient, Future<U>>)` to be rewritten to `SqlClient#withTransaction(io.reactivex.functions.Function<SqlClient, Single<U>>)`
=> Rx overloaded methods improvements

rx-java-gen/src/test/java/io/vertx/rx/java/test/WriteStreamSubscriberTest.java, rx-java2-gen/src/main/java/io/vertx/reactivex/impl/WriteStreamSubscriberImpl.java, rx-java2-gen/src/test/java/io/vertx/reactivex/test/WriteStreamSubscriberTest.java
Fixes #188
This was correctly implemented for RxJava 1 but not RxJava 2.
Added a test for both implementations.
=> RxJava2: always propagate WS error to subscriber callback

rx-java/src/main/asciidoc/vertx-rx/java/index.adoc
Motivation:
fix bad markdown syntax in document.
Conformance:
Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines
=> fix bad markdown syntax

rx-java/src/main/asciidoc/vertx-rx/java/index.adoc, rx-java2/src/main/asciidoc/vertx-rx/java2/index.adoc, rx-java3/src/main/asciidoc/vertx-rx/java3/index.adoc
Motivation:
According to the context in document, the subtitle "Rxified API" should have the same level as "Vert.x API for RxJava2"; but the former is in h1, the latter is in h2.
Conformance:
Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines
=> docs(): fix wrong title level in document

rx-junit5-providers/pom.xml, rx-junit5-providers/vertx-junit5-rx-java3/pom.xml, rx-junit5-providers/vertx-junit5-rx-java3/src/main/java/io/vertx/junit5/rxjava3/VertxParameterProvider.java, rx-junit5-providers/vertx-junit5-rx-java3/src/main/resources/META-INF/services/io.vertx.junit5.VertxExtensionParameterProvider, rx-junit5-providers/vertx-junit5-rx-java3/src/test/java/io/vertx/junit5/rxjava3/RxJava3Test.java
Closes #260
This allows to use vertx-junit5 with Vertx RxJava 3 API
=> Added vertx-junit5-rx-java3 module

rx-gen/src/test/java/io/vertx/lang/rx/test/ReadStreamSubscriberStaticsTestBase.java, rx-java-gen/src/main/java/io/vertx/rx/java/ReadStreamSubscriber.java, rx-java-gen/src/test/java/io/vertx/rx/java/test/ReadStreamSubscriberStaticsTest.java, rx-java2-gen/src/main/java/io/vertx/reactivex/impl/ReadStreamSubscriber.java, rx-java2-gen/src/test/java/io/vertx/reactivex/test/ReadStreamSubscriberStaticsTest.java, rx-java3-gen/src/main/java/io/vertx/rxjava3/impl/ReadStreamSubscriber.java, rx-java3-gen/src/test/java/io/vertx/rxjava3/test/ReadStreamSubscriberStaticsTest.java
Motivation:
Backport PR for Issue #200 / PR #266 for vertx 4.1
=> ReadStreamSubscriber does not properly handle errors delivered during subscribe

rx-gen/src/main/java/io/vertx/lang/rx/AbstractRxGenerator.java, rx-gen/src/main/java/io/vertx/lang/rx/DelegatingHandler.java, rx-java3/src/test/java/io/vertx/reactivex/test/CoreApiTest.java
Fixes #282
DelegatingHandler overrides hashCode/equals by invoking the delegate corresponding methods.
This fixes issues that we have when a handler can be added or removed from sets or lists.
=> Use DelegatingHandler for Handler params

pom.xml, rx-java/pom.xml, rx-java2/pom.xml, rx-java3/pom.xml
PrometheusMeterRegistry class is used in `@GenIgnore` method. But `micrometer-registry-prometheus` is a transitive dependency marked optional in `vertx-micrometer-metrics`
It needs to be explicitly added here. Otherwise, the build fails.
=> Add optional dependency to micrometer-registry-prometheus

rx-java2-gen/src/main/java/io/vertx/reactivex/impl/ObservableReadStream.java, rx-java3-gen/src/main/java/io/vertx/rxjava3/impl/ObservableReadStream.java
Motivation:
Stream handlers are defined in Subscription.set() - before calling onSubscribe on observer. For JDBCSQLRowStream setting handler causes readBatch() (https://github.com/vert-x3/vertx-jdbc-client/blob/1e9c8cb039735de6cc66400555da62093cfb7d7b/src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCSQLRowStream.java#L133). Sometimes emitting items from readBatch happens before calling o.onSubscribe(sub) in subscribeActual. For example, we can receive such exception if next operator after ObservableHelper.toObservable(readStream) is observeOn:
`
java.lang.NullPointerException: Cannot invoke "io.reactivex.internal.fuseable.SimpleQueue.offer(Object)" because "this.queue" is null
at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.onNext(ObservableObserveOn.jav …
=> ObservableReadStream: add pause before setting handlers and resume after onSubscribe

rx-gen/src/main/java/io/vertx/lang/rx/AbstractRxGenerator.java
Since JDK 8 javadoc requires strict HTML 4. A self-closing `<p/>` is no longer allowed and javadoc fails with
```
error: self-closing element not allowed
```
For details see https://stackoverflow.com/q/26049329
Replacing `<p/>` with `<p>` fixes the error.
=> Generate `<p>`, not `<p/>`, in javadoc, self-closing element not allowed

rx-java2/pom.xml, rx-java3/pom.xml
add rx2 and rx3 support for vertx-web-openapi and vertx-web-openapi-router
=> feat: instrument vertx-web-openapi and vertx-web-openapi-router

rx-gen/src/test/java/io/vertx/lang/rx/test/ReadStreamSubscriberTestBase.java, rx-java-gen/src/main/java/io/vertx/rx/java/ReadStreamSubscriber.java, rx-java2-gen/src/main/java/io/vertx/reactivex/impl/ReadStreamSubscriber.java, rx-java3-gen/src/main/java/io/vertx/rxjava3/impl/ReadStreamSubscriber.java
Linked to this issue: https://github.com/vert-x3/vertx-rx/issues/300
Ensure the ReadStream handler is never called concurrently.
=> 300 Make the ReadStreamSubscriber serialized

rx-gen/src/main/java/io/vertx/lang/rx/AbstractRxGenerator.java, rx-java-gen/src/main/java/io/vertx/lang/rxjava/RxJavaGenerator.java, rx-java2-gen/src/main/java/io/vertx/lang/reactivex/RxJava2Generator.java, rx-java3-gen/src/main/java/io/vertx/lang/rxjava3/RxJava3Generator.java
See #306
The equivalent methods for ReadStream (toObservable/toFlowable) were there already.
=> Add toObservable/toSubscriber methods to WriteStream contract

pom.xml, rx-java3-gen/src/main/java/io/vertx/rxjava3/impl/WriteStreamSubscriberImpl.java, rx-java3-gen/src/test/java/io/vertx/rxjava3/test/WriteStreamSubscriberTest.java
Fix rxJava 3 with the same fix as in https://github.com/vert-x3/vertx-rx/commit/9170efdbdf33322a09a16af9c1e7dbb736832f0a (see https://github.com/vert-x3/vertx-rx/pull/247)
RxJava3 has been forgotten when fixing this bug.
There is no need to call the RX onError handler since there is a potential Handler to call and the Subscriber is already done anyway
=> Up-port of the rxJava3 fix regarding throwing undeliverable error

rx-gen/src/main/java/io/vertx/lang/rx/AbstractRxGenerator.java, rx-java-gen/src/test/java/io/vertx/codegen/extra/DeprecatedMethod.java, rx-java-gen/src/test/java/io/vertx/codegen/extra/DeprecatedType.java, rx-java-gen/src/test/java/io/vertx/rx/java/test/DeprecationTest.java, rx-java2-gen/src/test/java/io/vertx/codegen/extra/DeprecatedMethod.java, rx-java2-gen/src/test/java/io/vertx/codegen/extra/DeprecatedType.java, rx-java2-gen/src/test/java/io/vertx/reactivex/test/DeprecationTest.java, rx-java3-gen/src/test/java/io/vertx/codegen/extra/DeprecatedMethod.java, rx-java3-gen/src/test/java/io/vertx/codegen/extra/DeprecatedType.java, rx-java3-gen/src/test/java/io/vertx/rxjava3/test/DeprecationTest.java
If the corresponding Vert.x API is deprecated, the Rx API must be deprecated as well.
This will help users upgrade their applications incrementally.
=> Mark Rx types as deprecated if needed

pom.xml
The previous version was released in 2021. This version change mandates a dependency update in Vert.x Infinispan too
=> Upgrade to RxJava3 version 3.1.10
