- rx-java/src/main/asciidoc/cheatsheet/HttpClientOptions.adoc
- rx-java/src/test/java/io/vertx/rx/java/test/api/ApiTest.java
Add new TCK test verifying the support of method receiving a list or a set of data objects.
> List and set of data object as param tck test

- rx-java/src/main/java/io/vertx/rx/java/ContextScheduler.java
- rx-java/src/test/java/io/vertx/rx/java/test/SchedulerTest.java
If you call an observable that calls back on a different thread the offload via observeOn (Scheduler) does not return on the correct thread.
In our case we were calling couchbase rxApi for inserting ext and it returns on an internal thread. Offloading it makes scense so we do not pollute our vertx thread with couchbase threads. In this case we get the wrong thread back and it causes some erratic bahaviour later on.
@See SchedulerTest.java:testScheduleObserveOnReturnsOnCorrectThread
@See ContextScheduler.java
> Context scheduler does not offload to the correct thread from external thread.

- rx-java/src/test/java/META-INF/MANIFEST.MF
- rx-java/src/test/java/io/vertx/rx/java/test/api/ApiTest.java
See https://github.com/vert-x3/issues/issues/85
> Test for handler return codegen

- rx-java/src/main/resources/vertx-rxjava/template/common.templ
- rx-java/src/test/java/io/vertx/rx/java/test/api/FunctionParamTCKTest.java
Support for codegen function params:
```
void filter(Function<String, Boolean> predicate);
```
please review.
> Support for function params

- rx-java/src/main/java/io/vertx/rxjava/core/RxHelper.java
- rx-java/src/test/java/io/vertx/rx/java/test/JavaIntegrationTest.java
> Add deployVerticle(Verticle verticle) to RxHelper.

- rx-java/src/main/asciidoc/java/index.adoc
- rx-java/src/main/java/examples/RxifiedExamples.java
- rx-java/src/main/java/io/vertx/rx/java/ContextScheduler.java
- rx-java/src/main/java/io/vertx/rxjava/core/RxHelper.java
- rx-java/src/main/java/io/vertx/rxjava/core/package-info.java
- rx-java/src/test/java/META-INF/MANIFEST.MF
- rx-java/src/test/java/io/vertx/rx/java/test/SchedulerTest.java
Added a new scheduler implementation backed by a named worker pool
> Solves #45 RxHelper should have an api to use WorkerExecutor

- rx-java/src/main/java/io/vertx/rx/java/ContextScheduler.java
> WorkerExecutorInternal#owner returns a Vert.x instance

- rx-java/src/main/java/io/vertx/rx/java/ContextScheduler.java
> Fixes #83 ContextImpl no longer allows to create a WorkerExecutor

- rx-groovy/src/main/java/io/vertx/rx/groovy/RxHelper.java
- rx-groovy/src/test/groovy/testHttpClientFlatMapUnmarshallTypeRef.groovy
- rx-groovy/src/test/java/io/vertx/rx/groovy/test/GroovyIntegrationTest.java
- rx-java/src/main/java/io/vertx/rx/java/RxHelper.java
- rx-java/src/main/java/io/vertx/rx/java/UnmarshallerOperator.java
- rx-java/src/test/java/io/vertx/rx/java/test/BufferTest.java
> Unmarshal Jackson TypeRefernce

- rx-java2/src/main/java/io/vertx/reactivex/core/RxHelper.java
- rx-java2/src/test/java/io/vertx/reactivex/test/RxHelperTest.java
Fixes vert-x3/vertx-examples#224
Issue not found while porting features from RxJava module
> IllegalArgumentException when calling RxHelper.deployVerticle (RxJava2)

- README.md
- rx-java/pom.xml
- rx-java/src/main/asciidoc/java/index.adoc
- rx-java/src/main/java/io/vertx/rxjava/core/package-info.java
- rx-java2/pom.xml
- rx-java2/src/main/asciidoc/java2/index.adoc
- rx-java2/src/main/java/io/vertx/reactivex/package-info.java
See Issue [#117](https://github.com/vert-x3/vertx-rx/issues/117).
> Add Doc for dependency usage in rxjava and rxjava2

- rx-java/src/main/java/io/vertx/rxjava/core/RxHelper.java
> Added method RxHelper.blockingScheduler(vertx, ordered)

- rx-java-codegen/src/main/java/io/vertx/lang/rxjava/AbstractRxGenerator.java
The current Model should not be related to whether the link is translate
> Fix the bug of `renderLinkToHtml`

- rx-java/src/main/asciidoc/vertx-cassandra-client/java/override/rxjava.adoc
- rx-java/src/main/java/examples/CassandraClientExamples.java
- rx-java/src/main/java/examples/RxCassandraClientExamples.java
Related to "extra doc for vertx-rx" in https://github.com/vert-x3/vertx-cassandra-client/issues/11
> Cassandra client examples

- rx-java2/src/main/asciidoc/vertx-cassandra-client/java/override/rxjava2.adoc
- rx-java2/src/main/asciidoc/vertx-mongo-client/java/override/rxjava2.adoc
- rx-java2/src/main/java/examples/RxCassandraClientExamples.java
- rx-java2/src/main/java/examples/RxMongoClientExamples.java
Improved Cassandra Rx docs and added Rx initial docs for Mongo
> Improved Rx docs

- rx-java/pom.xml
- rx-java2/pom.xml
- rx-java2/src/main/asciidoc/vertx-web-api-contract/java/override/rxjava2.adoc
- rx-java2/src/main/java/examples/RxWebApiContractExamples.java
Solve https://github.com/vert-x3/issues/issues/421
> Added vertx-web-api-contract to gen

- rx-java2-gen/src/main/java/io/vertx/reactivex/CompletableHelper.java
- rx-java2-gen/src/main/java/io/vertx/reactivex/MaybeHelper.java
- rx-java2-gen/src/main/java/io/vertx/reactivex/SingleHelper.java
- rx-java2/src/main/asciidoc/vertx-rx/java2/index.adoc
- rx-java2/src/main/java/examples/RxifiedExamples.java
> RxJava2: missing adpaters for async result handlers

- rx-java/pom.xml
- rx-java2/pom.xml
- rx-java2/src/main/asciidoc/vertx-web-graphql/java/override/rxjava2.adoc
> Document usage of GraphQL handler with RxJava

- rx-gen/src/main/java/io/vertx/lang/rx/AbstractRxGenerator.java
- rx-java-gen/src/main/java/io/vertx/lang/rxjava/RxJavaGenerator.java
- rx-java2-gen/src/main/java/io/vertx/lang/reactivex/RxJava2Generator.java
Follows-up on https://github.com/vert-x3/vertx-codegen/pull/253
> ReadStream and Write stream args moved to model

- rx-java-gen/src/test/java/io/vertx/codegen/testmodel/package-info.java
- rx-java2-gen/src/test/java/io/vertx/codegen/testmodel/package-info.java
- rx-java2-gen/src/test/java/io/vertx/reactivex/test/JsonCodecTCKTest.java
No changes to production code are required, I just add a test. https://github.com/vert-x3/vertx-codegen/issues/235
> Added test for new DataObject/Json Codec

- rx-java/src/main/java/io/vertx/rxjava/ext/sql/SQLClientHelper.java
- rx-java/src/test/java/io/vertx/rxjava/ext/sql/UsingConnectionSafetyTest.java
- rx-java2/src/main/java/io/vertx/reactivex/ext/sql/SQLClientHelper.java
- rx-java2/src/test/java/io/vertx/reactivex/ext/sql/UsingConnectionSafetyTest.java
> SQLClientHelper should close connection when user-provided code fails

- pom.xml
> Update RxJava 2 version

- rx-java/pom.xml
- rx-java2/pom.xml
Links to https://github.com/eclipse-vertx/vertx-json-schema/issues/1
> Added vertx-json-schema

- rx-java/pom.xml
- rx-java2/pom.xml
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
> Added vertx-web-validation

- rx-java/pom.xml
- rx-java2/pom.xml
For https://github.com/eclipse-vertx/vertx-sql-client/issues/696
> Add vertx-db2-client

- rx-java/pom.xml
- rx-java2/pom.xml
> Added Vert.x Web Session Store with Cookie and Redis

- rx-java/pom.xml
- rx-java2/pom.xml
- rx-java3/pom.xml
Signed-off-by: Paulo Lopes <pmlopes@gmail.com>
Motivation:
Adding vertx-auth-otp
> Adding vertx-auth-otp

- rx-java/pom.xml
- rx-java2/pom.xml
- rx-java3/pom.xml
Signed-off-by: Paulo Lopes <pmlopes@gmail.com>
> CVE-2021-44832: bump log4j

- README.adoc
- rx-java/src/main/asciidoc/vertx-rx/java/index.adoc
- rx-java2/src/main/asciidoc/vertx-rx/java2/index.adoc
Closes https://github.com/vert-x3/issues/issues/596
> Add warning in docs about missing bindings

- .github/workflows/ci.yml
- pom.xml
- rx-java/pom.xml
- rx-java2/pom.xml
- rx-java3/pom.xml
Oracle Client Rx bindings are not present in the stack yet
> Added Vert.x Oracle Client

- rx-java3/src/main/asciidoc/vertx-web-graphql/java/override/rxjava3.adoc
- rx-java3/src/main/java/examples/RxWebGraphQLExamples.java
- rx-java3/src/main/java/io/vertx/rxjava3/ext/web/handler/graphql/instrumentation/MaybeAdapter.java
- rx-java3/src/main/java/io/vertx/rxjava3/ext/web/handler/graphql/instrumentation/SingleAdapter.java
See https://github.com/vert-x3/vertx-web/issues/2329
> Instrumentation for reactive data fetchers

- rx-java3/src/main/java/io/vertx/rxjava3/core/AbstractVerticle.java
Fixes https://github.com/vert-x3/vertx-rx/issues/290
> Add abstract modifier to AbstractVerticle class

- rx-java-gen/src/main/java/io/vertx/rx/java/ContextScheduler.java
- rx-java-gen/src/test/java/io/vertx/rx/java/test/SchedulerTest.java
- rx-java2-gen/src/main/java/io/vertx/reactivex/ContextScheduler.java
- rx-java2-gen/src/test/java/io/vertx/reactivex/test/SchedulerTest.java
- rx-java2-gen/src/test/java/io/vertx/reactivex/test/WriteStreamSubscriberTest.java
- rx-java3-gen/src/main/java/io/vertx/rxjava3/ContextScheduler.java
- rx-java3-gen/src/test/java/io/vertx/rxjava3/test/SchedulerTest.java
- rx-java3-gen/src/test/java/io/vertx/rxjava3/test/WriteStreamSubscriberTest.java
> ContextScheduler must not schedule timed action after ContextWorker is canceled

- rx-java2/pom.xml
- rx-java3/pom.xml
Add rx2 and rx3 support for vertx-web-openapi-router
> feat: instrument vertx-web-openapi-router

- rx-gen/src/test/java/io/vertx/lang/rx/test/ReadStreamSubscriberTestBase.java
- rx-java-gen/src/main/java/io/vertx/rx/java/ReadStreamSubscriber.java
- rx-java2-gen/src/main/java/io/vertx/reactivex/impl/ReadStreamSubscriber.java
- rx-java3-gen/src/main/java/io/vertx/rxjava3/impl/ReadStreamSubscriber.java
Cherry-picked from 4.x branch
Ensure the ReadStream handler is never called concurrently.
Note: The Rx1 implementation is different because such stack are possible:
```
at io.vertx.rx.java.ReadStreamSubscriber.onNext(ReadStreamSubscriber.java:244) <-- won't emit its element since `emitting == true`
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowPath(OnSubscribeFromIterable.java:117)
at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:89)
at rx.Subscriber.request(Subscriber.java:157)
at io.vertx.rx.java.ReadStreamSubscriber.lambda$checkStatus$3(ReadStreamSubscriber.java:175)
at io.vertx.rx.java.ReadStreamSubscriber.checkStatus(ReadStreamSubscriber.java:190 …
```
> 300 Make the ReadStreamSubscriber serialized

- rx-java3/pom.xml
See https://github.com/vert-x3/issues/issues/646
> Add Web Proxy

- rx-gen/src/main/java/io/vertx/lang/rx/AbstractRxGenerator.java
- rx-gen/src/main/java/io/vertx/lang/rx/RxDelegate.java
- rx-java2-gen/src/main/java/io/vertx/lang/reactivex/Helper.java
- rx-java2/src/test/java/io/vertx/reactivex/tests/WebTest.java
- rx-java2/src/test/java/io/vertx/reactivex/tests/package-info.java
- rx-java2/src/test/java/io/vertx/reactivex/tests/web/TestRouteHandler.java
- rx-java2/src/test/java/io/vertx/reactivex/tests/web/impl/TestRouteHandlerImpl.java
- rx-java3-gen/src/main/java/io/vertx/lang/rxjava3/Helper.java
- rx-java3/src/test/java/io/vertx/rxjava3/tests/WebTest.java
- rx-java3/src/test/java/io/vertx/rxjava3/tests/package-info.java
- rx-java3/src/test/java/io/vertx/rxjava3/tests/web/TestRouteHandler.java
- rx-java3/src/test/java/io/vertx/rxjava3/tests/web/impl/TestRouteHandlerImpl.java
> Improve conversion of reactive handlers

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- rx-java2/pom.xml
- rx-java3/pom.xml
Follows-up on https://github.com/vert-x3/vertx-infinispan/pull/148
ISPN 15 requires JDK17
> Use Maven toolchains for rxjava2 and rxjava3
